//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vsar.TSBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vsar.TSBot.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approvals.
        /// </summary>
        internal static string Approvals {
            get {
                return ResourceManager.GetString("Approvals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deployment is approved..
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication is required..
        /// </summary>
        internal static string AuthenticationRequired {
            get {
                return ResourceManager.GetString("AuthenticationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build with id {0} is queued..
        /// </summary>
        internal static string BuildQueued {
            get {
                return ResourceManager.GetString("BuildQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builds.
        /// </summary>
        internal static string Builds {
            get {
                return ResourceManager.GetString("Builds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}. I have connected you to your team project &apos;{2}&apos;, which is in account &apos;{1}&apos;..
        /// </summary>
        internal static string ConnectedTo {
            get {
                return ResourceManager.GetString("ConnectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an account to connect to..
        /// </summary>
        internal static string ConnectToAccount {
            get {
                return ResourceManager.GetString("ConnectToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a project to connect to..
        /// </summary>
        internal static string ConnectToProject {
            get {
                return ResourceManager.GetString("ConnectToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been Disconnected..
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Error occurred:** {0}.
        /// </summary>
        internal static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am here to help you. Please select one of the following commands..
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect to another account through &apos;connect&apos;; Get your approvals by typing or clicking &apos;approvals&apos;; With &apos;builds&apos; you can queue a build; And with &apos;releases&apos; you can create a release..
        /// </summary>
        internal static string HelpAll {
            get {
                return ResourceManager.GetString("HelpAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please first &apos;connect&apos; to your account, by clicking or typing connect..
        /// </summary>
        internal static string HelpConnect {
            get {
                return ResourceManager.GetString("HelpConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a comment..
        /// </summary>
        internal static string MissingComment {
            get {
                return ResourceManager.GetString("MissingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no approvals available for you.
        /// </summary>
        internal static string NoApprovals {
            get {
                return ResourceManager.GetString("NoApprovals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no builds available..
        /// </summary>
        internal static string NoBuilds {
            get {
                return ResourceManager.GetString("NoBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no releases available..
        /// </summary>
        internal static string NoReleases {
            get {
                return ResourceManager.GetString("NoReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login to Visual Studio Team Services. After login you will receive a five digit pin number, please enter the pin number..
        /// </summary>
        internal static string PleaseLogin {
            get {
                return ResourceManager.GetString("PleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        internal static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Build.
        /// </summary>
        internal static string QueueBuild {
            get {
                return ResourceManager.GetString("QueueBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QueueRelease.
        /// </summary>
        internal static string QueueRelease {
            get {
                return ResourceManager.GetString("QueueRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deployment is rejected..
        /// </summary>
        internal static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release with id {0} is created..
        /// </summary>
        internal static string ReleaseCreated {
            get {
                return ResourceManager.GetString("ReleaseCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releases.
        /// </summary>
        internal static string Releases {
            get {
                return ResourceManager.GetString("Releases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I did not recognize that command. Please select one of the following commands..
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your personal user data has been deleted..
        /// </summary>
        internal static string UserDataDeleted {
            get {
                return ResourceManager.GetString("UserDataDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}. Good to see you. I will help you with your Visual Studio Team Services tasks. Please read the [EULA]({1}) if you have not done so..
        /// </summary>
        internal static string WelcomeUser {
            get {
                return ResourceManager.GetString("WelcomeUser", resourceCulture);
            }
        }
    }
}
